In [65]:
import numpy as np

from utils import *
from benchmark import results2np


In [66]:
# t = np.load('Benchmark/DE_BB_improve.npy')

In [67]:

guidelines_A6 = load_pickle('Benchmark/BB_A6.pickle')
results_B1 = load_pickle('Benchmark/BB_improv_A6_v3.pickle')
results_B2 = load_pickle('Benchmark/BB_improv_A6_v2.pickle')
results_B3 = load_pickle('Benchmark/BB_improv_A6_v4.pickle')


BB_A3 = load_pickle('Benchmark/BB_improv_A3_v3.pickle')
NBB_A3_bounds = load_pickle('Benchmark/NBB_improv_A3_bounds.pickle')
NBB_A3_bp = load_pickle('Benchmark/NBB_improv_A3_bp.pickle')
NBB_A3_full =load_pickle('Benchmark/NBB_improv_A3_full.pickle')


BB_A6 = load_pickle('Benchmark/BB_improv_A6_v2.pickle')
BB_A6_NP = load_pickle('Benchmark/BB_improv_A6_v2_biggerNP.pickle')
NBB_A6_bounds = load_pickle('Benchmark/NBB_improv_A6_bounds.pickle')
NBB_A6_bp = load_pickle('Benchmark/NBB_improv_A6_bp.pickle')
NBB_A6_full =load_pickle('Benchmark/NBB_improv_A6_full.pickle')



In [64]:
results = NBB_A3_bp
for r in results:
    print(f"{r['optimum']}\\textbackslash {r['restart']}", end=" & ")
print("\\\\")


10\textbackslash 0 & 10\textbackslash 0 & 10\textbackslash 0 & 10\textbackslash 3 & 10\textbackslash 5 & 10\textbackslash 0 & \\


In [72]:
# np_arr = results2np(results_A3, results_A6)


NBB_A6_bounds[-1]

{'evaluations': [887760,
  5000400,
  1516320,
  1379700,
  1453140,
  466560,
  412020,
  853200,
  1544400,
  393660],
 'avg_obj_vals': [0.49999842760736257,
  0.49980396862744714,
  0.49999772492198646,
  0.4999952665821209,
  0.49999764457381357,
  0.4999983361978005,
  0.4999987422381546,
  0.4999979495963607,
  0.49999770652630765,
  0.499998014587963],
 'best_obj_vals': [0.4999990162408598,
  0.499803971608148,
  0.4999990751077165,
  0.4999990252793011,
  0.49999912937142266,
  0.4999990273999492,
  0.49999903476969454,
  0.49999900491188837,
  0.49999911751079695,
  0.49999902380244676],
 'exitflag': [1, -1, 1, 1, 1, 1, 1, 1, 1, 1],
 'optimum': 9,
 'restart': 18}

In [4]:
# np.save('Benchmark/DE_BB_improve', np_arr)

In [5]:
np_arr

array([[[    660,     480,     360,     600,     540,     540,     600,
             480,     480,     540],
        [   4320,    4560,    4440,    5640,    2760,    4920,    4440,
            3240,    4200,    4800],
        [  49500,   23850,   19650,   30750,   23550,   36450,   38400,
           23850,   26250,   21300],
        [ 182880,   96840,  129420,  185580,   88920,  137520,  118980,
          286740,  615960,  282420],
        [ 140070,  253680,  764190,  603750, 1554210,  263760,  353850,
          240870,  779520,  598920],
        [1134810,  449820,  600210,  518940,  784080,  714150,  674190,
          602100,  767070,  399060]],

       [[   1120,     880,    1120,    1040,    1120,    1120,    1520,
             800,    1360,     720],
        [  12640,   12000,   11680,   10560,   11680,    6400,    9440,
            8000,    9600,   11200],
        [  68200,   70400,   55000,   52000,   50400,   47800,   63600,
           53400,   71400,   63200],
        [ 266400,

In [7]:
np_arr = np.load('Benchmark/DE_BB_improve.npy')

In [8]:
list(np_arr)

[array([[    660,     480,     360,     600,     540,     540,     600,
             480,     480,     540],
        [   4320,    4560,    4440,    5640,    2760,    4920,    4440,
            3240,    4200,    4800],
        [  49500,   23850,   19650,   30750,   23550,   36450,   38400,
           23850,   26250,   21300],
        [ 182880,   96840,  129420,  185580,   88920,  137520,  118980,
          286740,  615960,  282420],
        [ 140070,  253680,  764190,  603750, 1554210,  263760,  353850,
          240870,  779520,  598920],
        [1134810,  449820,  600210,  518940,  784080,  714150,  674190,
          602100,  767070,  399060]]),
 array([[   1120,     880,    1120,    1040,    1120,    1120,    1520,
             800,    1360,     720],
        [  12640,   12000,   11680,   10560,   11680,    6400,    9440,
            8000,    9600,   11200],
        [  68200,   70400,   55000,   52000,   50400,   47800,   63600,
           53400,   71400,   63200],
        [ 266400,

In [3]:
t

array([[[    100,     160,     100,     160,     240,     180,     100,
              60,     180,     160],
        [   1640,    3480,    3160,    1200,    1680,    2840,    1920,
            2320,    1000,     760],
        [  17900,    9700,   25600,   16900,   19300,   21050,   11600,
           13900,   34400,   17350],
        [ 556620,  335400,  301800,  155580,  832680,  169980,  208080,
          414900,  399480,  332520],
        [1263640, 4863180, 4901470, 1819930, 5000030, 5000030, 4656190,
         5000030, 3325910, 1766800],
        [2341620, 3131910, 2669400, 2002950, 3572550, 4103640, 2483910,
         2896290, 1096830, 3198690]],

       [[   1120,     880,    1120,    1040,    1120,    1120,    1520,
             800,    1360,     720],
        [  12640,   12000,   11680,   10560,   11680,    6400,    9440,
            8000,    9600,   11200],
        [  68200,   70400,   55000,   52000,   50400,   47800,   63600,
           53400,   71400,   63200],
        [ 266400,

In [7]:
results_A6

[{'evaluations': [1120, 880, 1120, 1040, 1120, 1120, 1520, 800, 1360, 720],
  'avg_obj_vals': [1.180254877621381,
   1.2027914363885062,
   1.203351808106688,
   1.2404093548180541,
   1.195180623645633,
   1.227081141559906,
   1.2923923753109272,
   1.0954936341843586,
   1.2786143995982213,
   1.0792918526290731],
  'best_obj_vals': [1.4142135623730951,
   1.4142135623730951,
   1.4142135623730951,
   1.4142135623730951,
   1.4142135623730951,
   1.4142135623730951,
   1.4142135623730951,
   1.4142135623730951,
   1.4142135623730951,
   1.4142135623730951],
  'exitflag': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
  'optimum': 10},
 {'evaluations': [12640,
   12000,
   11680,
   10560,
   11680,
   6400,
   9440,
   8000,
   9600,
   11200],
  'avg_obj_vals': [0.9371806140750671,
   0.8831026582217001,
   0.9330378806233609,
   0.8460954873445594,
   0.8628409358782692,
   0.7536039704851826,
   0.7834405082608322,
   0.7776058333452607,
   0.8693430709705566,
   0.8509271376785861],
  'best_ob